'use client';

import { useEffect, useRef, useState } from 'react';
import { Eraser, Mic, PenLine, StickyNote, Timer, X } from 'lucide-react';

type Tool = 'write' | 'focus' | 'voice' | 'snips';

export function StudyToolsOrb() {
  const [open, setOpen] = useState(false); const [tool, setTool] = useState<Tool | null>(null); const [pos, setPos] = useState({ x: 28, y: 120 }); const [tablet, setTablet] = useState(false); const [seconds, setSeconds] = useState(25 * 60); const [running, setRunning] = useState(false); const [recording, setRecording] = useState(false); const [note, setNote] = useState(''); const [savedSnips, setSavedSnips] = useState<string[]>([]); const [recordingUrl, setRecordingUrl] = useState<string | null>(null);
  const drag = useRef<{ x: number; y: number; moved: boolean } | null>(null); const canvas = useRef<HTMLCanvasElement>(null); const media = useRef<MediaRecorder | null>(null);
  useEffect(() => { const query = window.matchMedia('(pointer: coarse) and (min-width: 600px)'); const sync = () => setTablet(query.matches); sync(); query.addEventListener('change', sync); return () => query.removeEventListener('change', sync); }, []);
  useEffect(() => { try { const saved: unknown = JSON.parse(window.localStorage.getItem('zilu.studySnips.v1') ?? '[]'); if (Array.isArray(saved)) setSavedSnips(saved.filter((item): item is string => typeof item === 'string').slice(-20)); } catch { /* Optional browser-local storage. */ } }, []);
  useEffect(() => { if (!running) return; const timer = window.setInterval(() => setSeconds((value) => value <= 1 ? 25 * 60 : value - 1), 1000); return () => window.clearInterval(timer); }, [running]);
  function down(event: React.PointerEvent<HTMLButtonElement>) { drag.current = { x: event.clientX - pos.x, y: event.clientY - pos.y, moved: false }; event.currentTarget.setPointerCapture(event.pointerId); }
  function move(event: React.PointerEvent<HTMLButtonElement>) { if (!drag.current) return; drag.current.moved = true; setPos({ x: Math.max(8, Math.min(window.innerWidth - 60, event.clientX - drag.current.x)), y: Math.max(8, Math.min(window.innerHeight - 60, event.clientY - drag.current.y)) }); }
  function up() { const moved = drag.current?.moved; drag.current = null; if (!moved) setOpen((value) => !value); }
  function draw(event: React.PointerEvent<HTMLCanvasElement>) { const context = canvas.current?.getContext('2d'); if (!context || event.buttons !== 1) return; const rect = event.currentTarget.getBoundingClientRect(); context.fillStyle = '#191919'; context.beginPath(); context.arc((event.clientX - rect.left) * (620 / rect.width), (event.clientY - rect.top) * (360 / rect.height), 2.4, 0, Math.PI * 2); context.fill(); }
  async function toggleRecording() { if (recording) { media.current?.stop(); setRecording(false); return; } try { const stream = await navigator.mediaDevices.getUserMedia({ audio: true }); const chunks: Blob[] = []; const recorder = new MediaRecorder(stream); recorder.ondataavailable = (event) => chunks.push(event.data); recorder.onstop = () => { stream.getTracks().forEach((track) => track.stop()); setRecordingUrl(URL.createObjectURL(new Blob(chunks, { type: recorder.mimeType }))); }; recorder.start(); media.current = recorder; setRecording(true); } catch { window.alert('Allow microphone access to record your speaking practice.'); } }
  function saveSnippet() { const trimmed = note.trim(); if (!trimmed) return; const next = [...savedSnips, trimmed].slice(-20); setSavedSnips(next); setNote(''); try { window.localStorage.setItem('zilu.studySnips.v1', JSON.stringify(next)); } catch { /* The current session still retains it. */ } }
  const items: Array<[Tool, string, typeof PenLine]> = [["write", "Write", PenLine], ["focus", "Focus", Timer], ["voice", "Speak", Mic], ["snips", "Snips", StickyNote]];
  return <><button className="study-orb" aria-label="Study tools" style={{ left: pos.x, top: pos.y }} onPointerDown={down} onPointerMove={move} onPointerUp={up}><span lang="zh-Hant">工具</span></button>{open && <div className="orb-menu" style={{ left: pos.x, top: pos.y }}>{items.map(([id, label, Icon], index) => <button key={id} className={`orb-choice orb-choice-${index}`} onClick={() => { if (id === 'write' && !tablet) return; setTool(id); setOpen(false); }} disabled={id === 'write' && !tablet}><Icon /><span>{id === 'write' && !tablet ? 'Tablet' : label}</span></button>)}</div>}{tool && <aside className="orb-panel"><header><strong>{tool === 'write' ? 'Handwriting pad' : tool === 'focus' ? 'Focus timer' : tool === 'voice' ? 'Speaking recorder' : 'Study snippets'}</strong><button onClick={() => setTool(null)} aria-label="Close"><X /></button></header>{tool === 'write' && <><canvas ref={canvas} className="study-canvas" width="620" height="360" onPointerMove={draw} /><button className="study-secondary" onClick={() => canvas.current?.getContext('2d')?.clearRect(0, 0, 620, 360)}><Eraser /> Clear</button></>}{tool === 'focus' && <section className="tool-focus"><strong>{String(Math.floor(seconds / 60)).padStart(2, '0')}:{String(seconds % 60).padStart(2, '0')}</strong><button className="study-primary" onClick={() => setRunning((value) => !value)}>{running ? 'Pause' : 'Start 25 minutes'}</button></section>}{tool === 'voice' && <section className="tool-focus"><p>Record yourself saying a Chinese sentence. The recording stays in this browser tab until it is closed.</p><button className="study-primary" onClick={toggleRecording}>{recording ? 'Stop recording' : 'Start recording'}</button>{recordingUrl && <audio controls src={recordingUrl}>Your browser cannot play this recording.</audio>}</section>}{tool === 'snips' && <section><textarea className="study-notes" value={note} onChange={(event) => setNote(event.target.value)} placeholder="A sentence pattern, word, or mistake to revisit…" /><button className="study-primary" onClick={saveSnippet}>Save snippet</button><div className="tool-snips">{savedSnips.map((item, index) => <p key={`${item}-${index}`}>{item}</p>)}</div><p className="exam-small-note">Snippets are saved in this browser only.</p></section>}</aside>}</>;
}
